// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMiHGiec0kH9yE6qc8cpWYG5nEMeylClE',
    appId: '1:635085916931:web:93a6552649e2b795cd7736',
    messagingSenderId: '635085916931',
    projectId: 'flutter-insta-clone-76115',
    authDomain: 'flutter-insta-clone-76115.firebaseapp.com',
    storageBucket: 'flutter-insta-clone-76115.appspot.com',
    measurementId: 'G-F9VNBLFHTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dKMjpa2BW-aw7yn7iKvcVIC28PEFX8s',
    appId: '1:635085916931:android:a6f724e3a742d43fcd7736',
    messagingSenderId: '635085916931',
    projectId: 'flutter-insta-clone-76115',
    storageBucket: 'flutter-insta-clone-76115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp_rRYEy7XqqI2Ac35LjqzZcvhyKnuFEI',
    appId: '1:635085916931:ios:d8a4c3f785cdf78bcd7736',
    messagingSenderId: '635085916931',
    projectId: 'flutter-insta-clone-76115',
    storageBucket: 'flutter-insta-clone-76115.appspot.com',
    iosClientId: '635085916931-sslck5j75okq1lqfht2ald3v17sojqeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp_rRYEy7XqqI2Ac35LjqzZcvhyKnuFEI',
    appId: '1:635085916931:ios:d8a4c3f785cdf78bcd7736',
    messagingSenderId: '635085916931',
    projectId: 'flutter-insta-clone-76115',
    storageBucket: 'flutter-insta-clone-76115.appspot.com',
    iosClientId: '635085916931-sslck5j75okq1lqfht2ald3v17sojqeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
